var literales = {
    'dateMonth': new Array('Janeiro', 'Fevereiro', 'Mar&ccedil;o', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro')
};
var translations = {
    'errores': {
        'emptyfield': 'Por favor, preencha o formulário para continuar.',
        'postalcodeNotValid': 'Por favor, preencha o formulário para continuar.',
        'telephoneBlacklist': 'Para poder aconselhá-lo gratuitamente, precisamos de um número de telefone válido de você.',
        'telephoneDuplicated': 'Você já inseriu este número de telefone para salvar seu plano de segurança. Por favor, insira um número de telefone diferente.',
        'telephoneNotValid': 'O número de telefone está incorreto, digite um número de telefone válido.',
        'telephoneNotValidBr': 'Favor informar um número válido!',
        'telephoneWrongDDD': 'O número de DDD está incorreto, digite um número de DDD válido.',
        'telephoneZero': 'Por favor, insira o seu DDD sem numeral zero na frente. Exemplo: (11) 11111-1111'
    },
    'funnel': {
        'home': 'casa',
        'business': 'Negócio',
        'flat': 'Apartamento',
        'chalet': 'chalé',
        'primary': 'primário',
        'second-home': 'Segunda residência',
        'insideUrban': 'Dentro do núcleo urbano',
        'outsideUrban': 'Fora do núcleo urbano',
        'streetLevel': 'À direita na via pública',
        'noGuardedUrbanization': 'Atrás do jardim da frente',
        'guardedUrbanization': 'Em um acesso comum',
        'garden': 'Jardim ou terreno',
        'balconyOrTerrace': 'Varanda ou terraço',
        'no-access': 'Não possui',
        'yes-grid': 'Sim',
        'no-grid': 'Não',
        'always': 'Sempre há alguém',
        'less2hours': 'Menos de 2 horas por dia',
        '2_4hours': 'Entre 2 e 5 horas',
        'more4hours': 'Mais de 5 horas',
        'yes-robbed': 'Sim',
        'no-robbed': 'Não',
        'shopRestaurant': 'Comércio de rua',
        'warehouse': 'Empresa em um centro comercial',
        'office': 'Fábrica em polígono industrial',
        'others': 'Escritório em um edifício empresarial',
        'onlyMe': '1 funcionário',
        '2_4employees': 'De 2 a 5 funcionários',
        'more4employees': 'Mais de 5 funcionários',
        'mornings': 'Somente pela manhã',
        'afternoons': 'Somente à tarde',
        'morningsAfternoons': 'Manhã e tarde',
        'nights': 'Noturno',
        '24hours': '24 horas',
        'hightValue': 'Grande valor',
        'mediumValue': 'Médio valor',
        'lowValue': 'Baixo valor'
    }
};
var codifications = {
    'toEDS': {
        'home': '01',
        'business': '02',
        'flat': '03',
        'chalet': '04',
        'primary': '05',
        'second-home': '06',
        'insideUrban': '07',
        'outsideUrban': '08',
        'streetLevel': '09',
        'noGuardedUrbanization': '10',
        'guardedUrbanization': '11',
        'garden': '12',
        'balconyOrTerrace': '13',
        'no-access': '14',
        'yes-grid': '15',
        'no-grid': '16',
        'always': '17',
        'less2hours': '18',
        '2_4hours': '19',
        'more4hours': '20',
        'yes-robbed': '21',
        'no-robbed': '22',
        'shopRestaurant': '23',
        'warehouse': '24',
        'office': '25',
        'others': '26',
        'onlyMe': '29',
        '2_4employees': '30',
        'more4employees': '31',
        'mornings': '32',
        'afternoons': '33',
        'morningsAfternoons': '34',
        'nights': '35',
        '24hours': '36',
        'hightValue': '37',
        'mediumValue': '38',
        'lowValue': '39'
    },
    'fromEDS': {
        '01': 'home',
        '02': 'business',
        '03': 'flat',
        '04': 'chalet',
        '05': 'primary',
        '06': 'second-home',
        '07': 'insideUrban',
        '08': 'outsideUrban',
        '09': 'streetLevel',
        '10': 'noGuardedUrbanization',
        '11': 'guardedUrbanization',
        '12': 'garden',
        '13': 'balconyOrTerrace',
        '14': 'no-access',
        '15': 'yes-grid',
        '16': 'no-grid',
        '17': 'always',
        '18': 'less2hours',
        '19': '2_4hours',
        '20': 'more4hours',
        '21': 'yes-robbed',
        '22': 'no-robbed',
        '23': 'shopRestaurant',
        '24': 'warehouse',
        '25': 'office',
        '26': 'others',
        '29': 'onlyMe',
        '30': '2_4employees',
        '31': 'more4employees',
        '32': 'mornings',
        '33': 'afternoons',
        '34': 'morningsAfternoons',
        '35': 'nights',
        '36': '24hours',
        '37': 'hightValue',
        '38': 'mediumValue',
        '39': 'lowValue'
    }
};
